version: "3.9"
services:
  payment:
   depends_on:
      mysql:
        condition: service_healty
   build: ../../payment
   environment:
      APPLICATION_PORT: 8081
      ENV: "development"
      DATA_SOURCE_URL: "root:Az@1358740@tcp(mysql:3306)/payments?charset=utf8mb4&parseTime=True&loc=Local"
  order:
   depends_on:
    mysql:
     condition: service_healty
   build: ../../order
   ports:
         "8080:8080"
   environment:
    APPLICATION_PORT: 8080
    ENV: "development"
    DATA_SOURCE_URL: "root:Az@1358740@tcp(mysql:3306)/orders?charset=utf8mb4&parseTime=True&loc=Local"
    PAYMENT_SERVICE_URL: "payment:8081"

  mysql:
    image: "mysql:8.0.30"
    environment:
      MYSQL_ROOT_PASSWORD: "Az@1358740"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pAz@1358740"]
      interval: 5s
      timeout: 5s
      retries: 20
 